package exceptions;

public class Problem14 {
	
	public static void main(String[] args) {
		
		try {
			Problem11.youJustDividedByZero();
		} catch (Problem10 e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
		} finally {
			System.out.println("#LookAtThisPhotograph");
		}
		
		
		
	}

}
